//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEI_SSMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public Contract()
        {
            this.PhotoMessage = new HashSet<PhotoMessage>();
        }
    
        public System.Guid ContractID { get; set; }
        public string ContractNo { get; set; }
        public string Customer { get; set; }
        public string Contact { get; set; }
        public string PhoneNo { get; set; }
        public string SecondAgent { get; set; }
        public string FirstAgent { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> IsDel { get; set; }
        public string Remark { get; set; }
    
        public virtual ICollection<PhotoMessage> PhotoMessage { get; set; }
    }
}
