//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEI_SSMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        public System.Guid GoodsID { get; set; }
        public string GoodsName { get; set; }
        public string Number { get; set; }
        public Nullable<System.Guid> TypeID { get; set; }
        public Nullable<System.Guid> SpecificationID { get; set; }
        public Nullable<decimal> RentPrice { get; set; }
        public Nullable<decimal> Freight { get; set; }
        public string GoodsNo { get; set; }
        public string PhotoNo { get; set; }
        public Nullable<decimal> SellingPrice { get; set; }
        public Nullable<decimal> Pledge { get; set; }
        public Nullable<int> Transportation { get; set; }
        public Nullable<int> IsDel { get; set; }
        public string Remark { get; set; }
    
        public virtual Specification Specification { get; set; }
    }
}
