//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEI_SSMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jobs
    {
        public Jobs()
        {
            this.Users = new HashSet<Users>();
        }
    
        public System.Guid JobID { get; set; }
        public string JobName { get; set; }
        public string Remark { get; set; }
    
        public virtual ICollection<Users> Users { get; set; }
    }
}
