//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEI_SSMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public System.Guid OrderDetailID { get; set; }
        public Nullable<System.Guid> OrderID { get; set; }
        public Nullable<System.Guid> GoodsID { get; set; }
        public Nullable<int> DealType { get; set; }
        public Nullable<decimal> SellingPrice { get; set; }
        public Nullable<decimal> RentPrice { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> PayTax { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<System.Guid> SellerID { get; set; }
        public Nullable<System.DateTime> DeliveryOn { get; set; }
        public Nullable<decimal> PledgePer { get; set; }
        public Nullable<decimal> PledgeTotal { get; set; }
        public Nullable<decimal> FreightPer { get; set; }
        public Nullable<decimal> FreightTotal { get; set; }
        public Nullable<int> Transportation { get; set; }
        public Nullable<decimal> ReturnPlegeAmount { get; set; }
        public Nullable<System.DateTime> PaymentOn { get; set; }
        public Nullable<int> RentDays { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> IsDel { get; set; }
        public string Remark { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
