//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEI_SSMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoMessage
    {
        public int PhotoID { get; set; }
        public Nullable<System.Guid> ContractID { get; set; }
        public Nullable<int> PhotoType { get; set; }
        public string PhotoPath { get; set; }
    
        public virtual Contract Contract { get; set; }
    }
}
