//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEI_SSMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specification
    {
        public Specification()
        {
            this.Goods = new HashSet<Goods>();
        }
    
        public System.Guid SpecificationID { get; set; }
        public string SpecificationName { get; set; }
        public Nullable<double> Lenght { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Height { get; set; }
        public string Remark { get; set; }
    
        public virtual ICollection<Goods> Goods { get; set; }
    }
}
