//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEI_SSMS_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SSMSEntities : DbContext
    {
        public SSMSEntities()
            : base("name=SSMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Goods> Goods { get; set; }
        public DbSet<Jobs> Jobs { get; set; }
        public DbSet<PhotoMessage> PhotoMessage { get; set; }
        public DbSet<Specification> Specification { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
